Typos in commands at README.md
nschloe/tuna pull request #169
Opened 2024-05-03 09:54 UTC by loumalouomega

Just fixing some typos in the commands shown in the README.md

2024-05-21 07:39 UTC, loumalouomega commented
Hello @nschloe

2024-11-20 10:36 UTC, loumalouomega commented
Hello @nschloe

2024-11-20 10:36 UTC, loumalouomega commented
> Hello @nschloe

👋

2025-01-28 09:14 UTC, hugovk requested changes

2025-01-28 09:14 UTC, hugovk commented on README.md
> +python -m cProfile -o program.prof yourfile.py
A space after `-m` is common but not required:
```console
❯ python -mcProfile
Found existing alias for "python". You should use: "p"
Usage: cProfile.py [-o output_file_path] [-s sort] [-m module | scriptfile] [arg] ...

❯ python -m cProfile
Found existing alias for "python". You should use: "p"
Usage: cProfile.py [-o output_file_path] [-s sort] [-m module | scriptfile] [arg] ...
```

2025-01-28 09:14 UTC, hugovk commented on README.md
> +python -X import time yourfile.py 2> import.log
`import time` is incorrect, it should be `importtime`: https://docs.python.org/3/using/cmdline.html#cmdoption-X

```suggestion
python -X importtime yourfile.py 2> import.log
```

2025-01-28 09:27 UTC, loumalouomega commented on README.md
> +python -m cProfile -o program.prof yourfile.py
```suggestion
python -m cProfile -o program.prof yourfile.py
```

2025-06-02 13:11 UTC, closed without merging